App\Other\Constraint\Violation\Violations Object
(
    [violations:protected] => Array
        (
            [0] => App\Other\Constraint\Violation\Violation Object
                (
                    [name:protected] => login
                    [violated:protected] => unique
                    [message:protected] => This field violates unique constraint
                )

            [1] => App\Other\Constraint\Violation\Violation Object
                (
                    [name:protected] => password_confirmation
                    [violated:protected] => same
                    [message:protected] => This value should be same as password
                )

        )

)

login===login
unique===unique
login===login
password_confirmation===unique
login===password_confirmation
password_confirmation===same
Error: Call to a member function setMessage() on null in /var/www/html/src/Other/Constraint/Violation/Violations.php:98
Stack trace:
#0 /var/www/html/src/Request/Core/Request.php(301): App\Other\Constraint\Violation\Violations->set(Object(App\Other\Constraint\Group\MessageGroup), 'Password does n...')
#1 /var/www/html/src/Request/Core/Request.php(305): App\Request\Core\Request->App\Request\Core\{closure}(Array)
#2 /var/www/html/src/Request/Core/Request.php(160): App\Request\Core\Request->setMessages()
#3 /var/www/html/src/EventListener/RequestListener.php(85): App\Request\Core\Request->validate()
#4 /var/www/html/vendor/symfony/event-dispatcher/Debug/WrappedListener.php(116): App\EventListener\RequestListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\RequestEvent), 'kernel.request', Object(Symfony\Component\HttpKernel\Debug\TraceableEventDispatcher))
#5 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(220): Symfony\Component\EventDispatcher\Debug\WrappedListener->__invoke(Object(Symfony\Component\HttpKernel\Event\RequestEvent), 'kernel.request', Object(Symfony\Component\HttpKernel\Debug\TraceableEventDispatcher))
#6 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(56): Symfony\Component\EventDispatcher\EventDispatcher->callListeners(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\RequestEvent))
#7 /var/www/html/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php(139): Symfony\Component\EventDispatcher\EventDispatcher->dispatch(Object(Symfony\Component\HttpKernel\Event\RequestEvent), 'kernel.request')
#8 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(157): Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher->dispatch(Object(Symfony\Component\HttpKernel\Event\RequestEvent), 'kernel.request')
#9 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(76): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#10 /var/www/html/vendor/symfony/http-kernel/Kernel.php(197): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#11 /var/www/html/vendor/symfony/runtime/Runner/Symfony/HttpKernelRunner.php(35): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#12 /var/www/html/vendor/autoload_runtime.php(29): Symfony\Component\Runtime\Runner\Symfony\HttpKernelRunner->run()
#13 /var/www/html/public/index.php(5): require_once('/var/www/html/v...')
#14 {main}
App\Other\Constraint\Violation\Violations Object
(
    [violations:protected] => Array
        (
            [0] => App\Other\Constraint\Violation\Violation Object
                (
                    [name:protected] => login
                    [violated:protected] => unique
                    [message:protected] => This field violates unique constraint
                )

            [1] => App\Other\Constraint\Violation\Violation Object
                (
                    [name:protected] => password_confirmation
                    [violated:protected] => same
                    [message:protected] => This value should be same as password
                )

        )

)

Error: Call to a member function setMessage() on null in /var/www/html/src/Other/Constraint/Violation/Violations.php:95
Stack trace:
#0 /var/www/html/src/Request/Core/Request.php(301): App\Other\Constraint\Violation\Violations->set(Object(App\Other\Constraint\Group\MessageGroup), 'Password does n...')
#1 /var/www/html/src/Request/Core/Request.php(305): App\Request\Core\Request->App\Request\Core\{closure}(Array)
#2 /var/www/html/src/Request/Core/Request.php(160): App\Request\Core\Request->setMessages()
#3 /var/www/html/src/EventListener/RequestListener.php(85): App\Request\Core\Request->validate()
#4 /var/www/html/vendor/symfony/event-dispatcher/Debug/WrappedListener.php(116): App\EventListener\RequestListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\RequestEvent), 'kernel.request', Object(Symfony\Component\HttpKernel\Debug\TraceableEventDispatcher))
#5 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(220): Symfony\Component\EventDispatcher\Debug\WrappedListener->__invoke(Object(Symfony\Component\HttpKernel\Event\RequestEvent), 'kernel.request', Object(Symfony\Component\HttpKernel\Debug\TraceableEventDispatcher))
#6 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(56): Symfony\Component\EventDispatcher\EventDispatcher->callListeners(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\RequestEvent))
#7 /var/www/html/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php(139): Symfony\Component\EventDispatcher\EventDispatcher->dispatch(Object(Symfony\Component\HttpKernel\Event\RequestEvent), 'kernel.request')
#8 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(157): Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher->dispatch(Object(Symfony\Component\HttpKernel\Event\RequestEvent), 'kernel.request')
#9 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(76): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#10 /var/www/html/vendor/symfony/http-kernel/Kernel.php(197): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#11 /var/www/html/vendor/symfony/runtime/Runner/Symfony/HttpKernelRunner.php(35): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#12 /var/www/html/vendor/autoload_runtime.php(29): Symfony\Component\Runtime\Runner\Symfony\HttpKernelRunner->run()
#13 /var/www/html/public/index.php(5): require_once('/var/www/html/v...')
#14 {main}
App\Other\Constraint\Violation\Violations Object
(
    [violations:protected] => Array
        (
            [0] => App\Other\Constraint\Violation\Violation Object
                (
                    [name:protected] => login
                    [violated:protected] => unique
                    [message:protected] => This field violates unique constraint
                )

            [1] => App\Other\Constraint\Violation\Violation Object
                (
                    [name:protected] => password_confirmation
                    [violated:protected] => same
                    [message:protected] => This value should be same as password
                )

        )

)

App\Other\Constraint\Violation\Violations Object
(
    [violations:protected] => Array
        (
            [0] => App\Other\Constraint\Violation\Violation Object
                (
                    [name:protected] => login
                    [violated:protected] => unique
                    [message:protected] => Login already exists
                )

            [1] => App\Other\Constraint\Violation\Violation Object
                (
                    [name:protected] => password_confirmation
                    [violated:protected] => same
                    [message:protected] => Password does not match!!!!
                )

        )

)

